import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import IChildrenProps from "@/interfaces/children-props";
import classNames from "@/util/classNames";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({children}: IChildrenProps) => {
  return (
    <html lang="en">
    <body className={classNames(
      "w-screen h-[100svh] bg-background-dark text-text"
    )}>
    {children}
    </body>
    </html>
  );
};

export default RootLayout;